### ISSUE TITLE
How to train different style model ?

### ISSUE THREAD

**Issue by WestbrookZero** [cumulo-autumn/StreamDiffusion#108]

**Comment by teftef6220** [comment]
You can do that in here.

https://github.com/kohya-ss/sd-scripts

**Comment by FCPotesD** [comment]
Adding to this, are there any extra steps I need to take in order to properly prepare a fine-tuned model for use with StreamDiffusion? I've tested this successfully with several fine tunes, and while they work, the results are super sub par, and I'm unsure if it's due to my model, or due to parameters I haven't thought to change. 

the model works great in Comfy and for stills, but becomes blurry as all hell (While still recognizable) in StreamDiffusion.
