### ISSUE TITLE
negative prompt support

### ISSUE THREAD

**Issue by NaCloudAI** [cumulo-autumn/StreamDiffusion#27]
can this be done?

**Comment by marianbastiUNRN** [comment]
Yes
When you prepare the stream
```python
stream.prepare(
    prompt=positive_prompt,
    negative_prompt=negative_prompt
    guidance_scale=guidance_scale,
    delta=delta,
)
```

**Comment by tegnike** [comment]
Or you can try as an option.

```
--negative_prompt "Bad quality"
```

https://github.com/cumulo-autumn/StreamDiffusion/tree/main/examples#negative-prompt

**Comment by NaCloudAI** [comment]
Sorry, I didn't make it clear. I meant the negative prompts used in the text-to-image generation. Without negative prompts, the overall quality of the images is low. Below is my comparison with CivitAI.

![image](https://github.com/cumulo-autumn/StreamDiffusion/assets/134971595/2d3899cc-75ad-4b83-9998-7960eb8451ae)


![image](https://github.com/cumulo-autumn/StreamDiffusion/assets/134971595/c803cb4d-1fb6-4384-a149-7d956e9e7a4f)


```
fashion photography portrait of indian girl with blue hair, in lush jungle with flowers, 3d render, cgi, symetrical, octane render, 35mm, bokeh, 9:16, (intricate details:1.12), hdr, (intricate details, hyperdetailed:1.15), (natural skin texture, hyperrealism, soft light, sharp:1.2), detailed, sunlight passing through foliage, india
```

for some reason they don't feel like the same model at all, could this be because I did not set a VAE?

**Comment by teftef6220** [comment]
Due to the use of LCM, we cannot guarantee the same quality as the output image of SD 1.5 model.
Because of the trade-off relationship between quality and generation speed, one or the other must be sacrificed.
Quality can be improved to some extent by varying `cfg_type` and `guidance_scale`.

VAE uses tynyVAE.
It is possible to change the VAE by changing the `vae_id` in `utils/wrapper.py`, but the generation speed will be reduced.
